Vidly/Models/Supermarket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Supermarket
    {
        public int SubmissionId { get; set; }
        public string Date { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public string Address { get; set; }
    }
}

Vidly/ViewModels/Supermarkets.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly.Models;

namespace Vidly.ViewModels
{
    public class Supermarkets
    {
        public List<Supermarket> SupermarketList { get; set; }
        public List<Supermarket> SearchedSupermarkets { get; set; }
        public bool JustStarted { get; set; }

    }
}

Vidly/Controllers/SupermarketController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class SupermarketController : Controller
    {
        // GET: Supermarket
        
        public ActionResult Index(string SearchString)
        {
            bool justStarted = true;
            Supermarkets s = new Supermarkets();
            List<Supermarket> supermarkets;
            List<Supermarket> searchedSupermarkets = new List<Supermarket>();
            using (StreamReader r = new StreamReader(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"Data\", "values.json")))
            {
                string json = r.ReadToEnd();
                supermarkets = JsonConvert.DeserializeObject<List<Supermarket>>(json);
                            
            }
            if (SearchString != null)
            {
                justStarted = false;
                foreach (Supermarket i in supermarkets)
                {
                    if (i.Address.IndexOf(SearchString, StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        searchedSupermarkets.Add(i);

                    }
                }

            }
            s.SupermarketList = supermarkets;
            s.SearchedSupermarkets = searchedSupermarkets;
            s.JustStarted = justStarted;

            return View(s);
        }
    }
}

Vidly/Views/Supermarket/Index.cshtml
@model Vidly.ViewModels.Supermarkets
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Supermarkets</h2>
@using (Html.BeginForm("Index", "Supermarket", FormMethod.Get))
{
    <p>
        Zoeken: @Html.TextBox("SearchString")<input type="submit" value="Zoek" />
    </p>
}





<ul>
    @if (Model.SearchedSupermarkets.Count != 0)
    {
        foreach (var supermarket in Model.SearchedSupermarkets)
        {
            <li>@supermarket.Address</li>
        }
    }
    else if (Model.JustStarted)
    {
        foreach (var supermarket in Model.SupermarketList)
        {
            <li>@supermarket.Address</li>
        }
    }
</ul>
@if (Model.SearchedSupermarkets.Count == 0&&Model.JustStarted==false)
{
    <p>No Supermarkets found</p>
}
<p>Dropdown:</p>
<select>
    @if (Model.SupermarketList.Count != 0)
    {
        foreach (var supermarket in Model.SupermarketList)
        {
            <option>@supermarket.Address</option>
        }
    }
</select>
<br/>
<br/>

<br/>
<p id="demo"></p>
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script type="text/javascript">
    var x = document.getElementById("demo");

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition, showError);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }

    function Coordinate(lat, lon) {
        this.lat = lat;
        this.lon = lon;
    }

    function showPosition(position) {
        var myLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        var mapProp = {
            center: myLocation,
            zoom: 7,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        addMarker(myLocation, map);
        }
    function addMarker(coordinate, map)
    {
        var marker = new google.maps.Marker({
            position: coordinate,
            map: map,
            draggable: false
        });
    }

    function showError(error) {
        if (error.code == 1) {
            x.innerHTML = "User denied the request for Geolocation.";
        } else if (error.code == 2) {
            x.innerHTML = "Location information is unavailable.";
        } else if (error.code == 3) {
            x.innerHTML = "The request to get user location timed out.";
        } else {
            x.innerHTML = "An unknown error occurred.";
        }
    }
    google.maps.event.addDomListener(window, 'load', getLocation);
</script>
<div id="googleMap" style="width:500px;height:380px;"></div>